### ISSUE TITLE
Jira Integration: jira.create_issue: request failed

### ISSUE THREAD

**Issue by raphaelquati** [grafana/incident-community#32]
I'm trying to set up Jira Integration to make a POC.
I'm the admin of our Jira account.

After create an incident, an error occurs:

```
HookRun.grate.jira.createIssue: jira.create_issue: request failed. 
Please analyze the request body for more details. Status Code: 400
```

![image](https://user-images.githubusercontent.com/815086/197679905-d3ff214f-f922-436f-8b76-f1bed5f4d4fd.png)

Browser: Edge 106.0.1370.52
Grafana: Cloud (v9.2.1-cab7049 (cab7049dd1))

**Comment by matryer** [comment]
Hey @raphaelquati thank you for reporting this. We'll look into providing a better error to start with, and we'll have a look to see what could be going on here.

**Comment by paulcoghlan** [comment]
Hi @raphaelquati - as @matryer mentioned we're going to improve the error reporting - meanwhile I'm wondering if this problem is due to the "Issue Type" that our Jira integration is using?

When we first released the Jira integration we created "Bug" type issues, however not everyone has this type of issue so now in the most recent release (`1.0.23`) we create "Task" type issues.

Would you mind re-testing and seeing if this works now?

**Comment by raphaelquati** [comment]
Hi @paulcoghlan, 
Clicking on the "refresh" button on the incident (to create the incident on Jira) does not work.

So, at the Integrations tab, I've removed the project link, and add again (now it's showing the ID of the Jira Project)

Now It's working.

Thanks
